# config.yaml
testnet:
    url: testurl
    rkuser: rkuser
    passwd: rkpwd
    chain: test-chain

mainnet:
    url: mainurl
    rkuser: rkuser
    passwd: rkpwd
    chain: main-chain




